Update vehicles.csv
Fixed innacuracies within Area 1's datasets:
 - Updated all conectos (1100-1423) to the following capacity: 29 seated | 82 standing
 - Updated all Ivecos (1700-1737) to have the following capacity: 15 seated | 10 standing.
  EXCEPTION: The Itrabus chassis ivecos (1732-1735) have a different capacity of 18 seated and 15 standing due to their larger size/wider body
 - Updated all Mercedes Atomics (306-335 and 722-729) to have a capacity of 37 seated and 52 standing, as per their manufacterer's specifications
- Updated all Atomic Minis (733-749) to have the correct capacity of 16 seated and 10 standing.
- Updated the older conectos (765-767 and 1901) to have the capacity of 30 seated and 56 standing. These conectos have an extra seat compared to the newer conectos
 - Updated the older citaros (810-819) to have the capacity that's stated onboard (30 seated, 55 standing)
- ADDED the new Citaro K hybrid (with id 823), that's been brought in from the touristic services back in April/25